spring:
  application:
    name: registry-service
  profiles:
    active: dev
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone=http://localhost:8761/eureka:

